version: "3"

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data:
  
services:
  poll:
    build: ./poll
    environment:
      POLL_HOST: poll
      PORT: 80
      REDIS_HOST: redis
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - poll-tier
    restart: unless-stopped

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    restart: unless-stopped

  worker:
    build: ./worker
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
    depends_on:
      - redis 
      - db
    networks:
      - back-tier
    restart: unless-stopped


  db:
    image: postgres:11
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - result-tier
      - back-tier
    restart: unless-stopped

  result:
    build: ./result
    environment:
      PORT: 80
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - result-tier
    restart: unless-stopped
